---
title: "`r html_title`"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,
                      fig.width=fig_width, fig.height=fig_height,
                      cache=FALSE, cache.lazy = FALSE,
                      fig.align='center')
```

```{=html}
<style type="text/css">
.book .book-body .page-inner {
  max-width: 1600px;
  margin-left: auto;
  margin-right: auto;
}
details > summary {
  display: list-item;
}
</style>
```


```{r, results="asis"}
plate_layouts_chunk_text <- c(
  '```{r}',
  'legend <- "{{col}}" %in% include_legend',
  'label <- "{{col}}" %in% include_label',
  'p <- OlinkAnalyze::olink_displayPlateLayout(
    data = plate_list[["{{plate}}"]], 
    fill.color = "{{col}}", include.label = label
    ) +
    ggplot2::ggtitle(paste0("{{plate}}", ": ", "{{col}}"))
  if (!legend) {
    p <- p + ggplot2::theme(legend.position = "none")
  }',
  'p',
  '```\n'
)

out <- NULL
for (plate in names(plate_list)) {
  out <- c(out, knitr::knit_expand(text = "## {{plate}} {.tabset}\n"))
  for (col in color_by) {
    out <- c(out, knitr::knit_expand(text = "### {{col}}"))
    out <- c(out, knitr::knit_expand(text = plate_layouts_chunk_text))
  }
}
cat(knitr::knit_child(text = out, quiet = TRUE), sep = '\n')
```
